# Generated by Django 5.1.5 on 2025-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoulDiaryConnectApp", "0002_rename_passwd_medico_password_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medico",
            options={"verbose_name": "Medico", "verbose_name_plural": "Medici"},
        ),
        migrations.AlterModelOptions(
            name="messaggio",
            options={"verbose_name": "Messaggio", "verbose_name_plural": "Messaggi"},
        ),
        migrations.AlterModelOptions(
            name="notadiario",
            options={
                "verbose_name": "Nota Diario",
                "verbose_name_plural": "Note Diario",
            },
        ),
        migrations.AlterModelOptions(
            name="paziente",
            options={"verbose_name": "Paziente", "verbose_name_plural": "Pazienti"},
        ),
        migrations.AddField(
            model_name="notadiario",
            name="emozione_predominante",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
